name: nbconvert6
channels:
 - conda-forge
dependencies:
 - python=3.6
 - notebook=6.0.0
 - nbconvert=5.6.1
 - jupyter_contrib_nbextensions=0.4.0
# - jupyter_nbextensions_configurator


# jupyter contrib nbextension install --user

# run jupyther notebook and activate
# Go to the Nvextensions tab, select the option for Table of Contents (2), and Enable it.
