name: python_spatial
channels:
 - pytorch
 - conda-forge
 - bioconda
 - defaults
 - anaconda
dependencies:
 - python=3.7
 - compilers
 - pip
 - jupyterlab
 - scanorama
 - nb_conda
 - pip:
   - scvi-tools[tutorials]
   - squidpy 



