## conda requirements for all packages needed to run the scanpy tutorials
# install with:  mamba env create -n scRNAseq2022 -f environment_scRNAseq2022.yml
# then run: source activate scRNAseq2022
name: rstudio

channels:
### MAIN CONDA CHANNELS ###
 - conda-forge
 - anaconda
 - bioconda
 - defaults
 - r
 - rdonnelly

dependencies:
### GENERAL LIBRARIES ###
 - rstudio>1.2
 - compilers
