name: scRNAseq2023_python
channels:
 - pytorch
 - conda-forge
 - bioconda
 - defaults
 - anaconda
dependencies:
 - python
 - compilers
 - pip
 - scanpy
 - numba
 - numpy=1.23.5
 - jupyterlab
 - scanorama
 - nb_conda
 - jupyter_contrib_nbextensions
 - scvi-tools
 - scrublet
 - bbknn
 - fa2   
 - python-igraph
 - pynndescent
 - leidenalg
 - louvain
 - mkl < 2022 # needed for running intel conda on M1 mac.
 - gseapy
 - scikit-learn
 - matplotlib-venn
 - pybiomart
